import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import CssBaseline from "@mui/material/CssBaseline/CssBaseline";
import ModeContextProvider from "@/src/contexts/modeContext";
import StyledEngineProvider from "@mui/styled-engine/StyledEngineProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <AppRouterCacheProvider>
          <StyledEngineProvider injectFirst>
            <ModeContextProvider>
              <CssBaseline />
              {children}
            </ModeContextProvider>
          </StyledEngineProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
